#:kivy 1.10.1
#:import Factory kivy.factory.Factory

<HomeScreen>:

    sm: sm
    name: 'ScreenManager'

    BoxLayout:
        orientation: 'vertical'
        rows: 2
        
        ActionBar:
            pos_hint: {'top': 1}
            size_hint_y: .065
            ActionView:
                use_separator: True
                
                ActionPrevious:
                    
                ActionOverflow:

                ActionButton:
                    text: 'Cocktails'
                    on_press:
                        root.switch(1)

                ActionButton:
                    text: 'Drinks'
                    on_press:
                        root.switch(2)

                ActionButton:
                    text: 'Alkoholfreies'
                    on_press:
                        root.switch(3)
                        
                ActionButton:
                    text: 'Einstellungen'
                    on_press:
                        root.switch(4)
            

        ScreenManager:
            id: sm
            size_hint_y: .935

            Screen1:
                
            Screen2:
                
            Screen3:

            Screen4:
                
                

##########################################################################

#----------------------- Screen 1 ------------------------
<Screen1@Screen>:
    name: "screen1"
    RV_Cocktails:

#----------------------- Screen 2 ------------------------
<Screen2@Screen>:
    name: "screen2"
    RV_Drinks:


#----------------------- Screen 3 ------------------------
<Screen3@Screen>:
    name: "screen3"
    RV_Alkoholfrei:


#----------------------- Screen 4 (Settings) ------------------------
<Screen4@Screen>:
    name: "screen4"
    ScrollView:
        do_scroll_x: False
        GridLayout:
            cols: 1
            spacing: 10
            size_hint: (.95, None)
            height: self.minimum_height
            
            Label:
                size_hint: (.9 ,None)
                height: '10dp'
                text: ''

            Label:
                size_hint: (.9 ,None)
                height: '20dp'
                text: 'Systemeinstellungen'

            BoxLayout:
                size_hint: (.9 ,None)
                height: '20dp'
                orientation: 'horizontal'
                Label:
                    text: 'Vollbildmodus'
                Switch:
                    id: 'fullscreen_switch'
                    on_active: root.fullscreenchanger(self.active)
            
            Label:
                size_hint: (.9 ,None)
                height: '5dp'
                text: ''
            Label:
                size_hint: (.9 ,None)
                height: '20dp'
                text: 'Fachinhalte'
            
            Fachinhalt_Setting:
                size_hint: (.9 ,None)
                height: '35dp'
                text: 'Fach 1'
            Fachinhalt_Setting:
                size_hint: (.9 ,None)
                height: '35dp'
                text: 'Fach 2'
            Fachinhalt_Setting:
                size_hint: (.9 ,None)
                height: '35dp'
                text: 'Fach 3'
            Fachinhalt_Setting:
                size_hint: (.9 ,None)
                height: '35dp'
                text: 'Fach 4'       

            Label:
                size_hint: (.9 ,None)
                height: '5dp'
                text: ''
            Label:
                size_hint: (.9 ,None)
                height: '20dp'
                text: 'Kalibrierungseinstellungen'

            Calibration_Setting:
                size_hint: (.9 ,None)
                height: '70dp'
                text: 'Kalibrierung Fach 1'
            Calibration_Setting:
                size_hint: (.9 ,None)
                height: '70dp'
                text: 'Kalibrierung Fach 2'
            Calibration_Setting:
                size_hint: (.9 ,None)
                height: '70dp'
                text: 'Kalibrierung Fach 3'
            Calibration_Setting:
                size_hint: (.9 ,None)
                height: '70dp'
                text: 'Kalibrierung Fach 4'
                              
            Label:
                size_hint: (.9 ,None)
                height: '5dp'
                text: ''

            BoxLayout:
                size_hint: (.9 ,None)
                height: '35dp'
                orientation: 'horizontal'
                Label:
                    text: 'Cocktailrezepte'
                Button:
                    text: 'Cocktailrezept hinzufuegen'
                    on_press: root.cockatil_adder()
                Button:
                    text: 'Cocktailrezept bearbeiten'
                    on_press: root.cockatil_editer()

            Label:
                size_hint: (.9 ,None)
                height: '5dp'
                text: ''

            Label:
                size_hint: (.9 ,None)
                height: '30dp'
                text: 'Version: 2.4'

########################################################################
########################################################################
<RV_Cocktails>:
    viewclass: 'RecycleViewRow_Cocktails'
    RecycleBoxLayout:
        default_size: dp(250), dp(56)
        default_size_hint: None, 1
        size_hint_x: None
        width: self.minimum_width
        orientation: 'horizontal'

<RecycleViewRow_Cocktails>:
    orientation: 'vertical'
    Image:
        source: root.image_source
        size_hint: (.9, .85)
    Label:
        size_hint: (.9, .05)
        text: root.rating
    Button:
        on_press: 
            root.show_rezept(root.text)
        text: root.text
        size_hint: (.95, .1)

<RV_Alkoholfrei>:
    viewclass: 'RecycleViewRow_Alkoholfrei'
    RecycleBoxLayout:
        default_size: dp(250), dp(56)
        default_size_hint: None, 1
        size_hint_x: None
        width: self.minimum_width
        orientation: 'horizontal'

<RecycleViewRow_Alkoholfrei>:
    orientation: 'vertical'
    Image:
        source: root.image_source
        size_hint: (.9, .85)
    Label:
        size_hint: (.9, .05)
        text: root.rating
    Button:
        on_press: 
            root.show_rezept(root.text)
        text: root.text
        size_hint: (.95, .1)

<RV_Drinks>:
    viewclass: 'RecycleViewRow_Drinks'
    RecycleBoxLayout:
        default_size: dp(250), dp(56)
        default_size_hint: None, 1
        size_hint_x: None
        width: self.minimum_width
        orientation: 'horizontal'

<RecycleViewRow_Drinks>:
    orientation: 'vertical'
    Image:
        source: root.image_source
        size_hint: (.9, .80)
    Label:
        size_hint: (.9, .05)
        text: root.drink_type
    Label:
        size_hint: (.9, .05)
        text: root.rating
    Button:
        on_press: 
            #app.show_description(root.text)
        text: root.text
        size_hint: (.95, .1)

######### Settings Widgets ################################
<Fachinhalt_Setting>:
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: root.text
        Spinner:
            name: root.fach_id
            text: root.current_fachinhalt
            values: root.drinks_list
            on_text: root.on_spinner_select(self.text, self.name)

<Calibration_Setting>:
    BoxLayout:
        orientation: 'horizontal'
        Label:
            text: root.text
        BoxLayout:
            orientation: 'vertical'

            BoxLayout:
                orientation: 'horizontal'
                Button:
                    name: root.fach_id_minusminus
                    size_hint_x: None
                    width: self.height * 2
                    text: '--'
                    on_press: root.on_kalibration_select(self.name)
                Button:
                    name: root.fach_id_minus
                    size_hint_x: None
                    width: self.height * 2
                    text: '-'
                    on_press: root.on_kalibration_select(self.name)
                Label:
                    name: root.fach_id
                    text: root.kalibrierungswert
                Button:
                    name: root.fach_id_plus
                    size_hint_x: None
                    width: self.height * 2
                    text: '+'
                    on_press: root.on_kalibration_select(self.name)
                Button:
                    name: root.fach_id_plusplus
                    size_hint_x: None
                    width: self.height * 2
                    text: '++'
                    on_press: root.on_kalibration_select(self.name)

            BoxLayout:
                orientation: 'horizontal'

                Button:
                    size_hint_: None
                    text: 'Testen mit 2cl'
                
                Button:
                    name: root.fach_id
                    size_hint_x: None
                    text: 'Speichern'
                    #background_color: 1, .3, .4, .85    
                    on_press: root.on_save_select(self.name)
                
########## Popups ######################

<Rezept>:
    auto_dismiss: False
    title: root.title
    size_hint: (.60, .80)
    BoxLayout:
        orientation: 'vertical'
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            Label:
                text: root.rezept
                size_hint_y: None
                text_size: self.width, None
                height: self.texture_size[1]
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (.95, .1)
            Button:
                text: 'Zurueck'
                on_release: root.dismiss()
            Button:
                text: 'Einschenken'


<cocktail_adder>:
    auto_dismiss: False
    title: 'Cocktail hinzufügen'
    size_hint: (.60, .80)
    BoxLayout:
        orientation: 'vertical'
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            GridLayout:
                cols: 2
                size_hint: 1, None
                height: self.minimum_height
            
                Label:
                    size_hint: .2, None
                    height: '30dp'
                    text_size: self.width, None
                    text: 'Name des Cocktails:'
                TextInput:
                    size_hint: 1.8, None
                    height: '30dp'
                    multiline: False

                Label:
                    text_size: self.width, None
                    text: 'Beschreibung:'
                TextInput:
                    size_hint: 1, None
                    height: max(self.minimum_height, self.height)

                Label:
                    text_size: self.width, None
                    text: 'Zubereitung:'
                TextInput:
                    size_hint: 1, None
                    height: max(self.minimum_height, self.height)

                Label:
                    text_size: self.width, None
                    text: 'Alkoholische Zutaten'
                Label:
                    text_size: self.width, None
                    size_hint: 1, None
                    text: ' '     

                    
                Label:
                    text_size: self.width, None
                    text: 'Mischgetränke'
                Label:
                    text_size: self.width, None
                    size_hint: 1, None
                    text: ' '       


                Label:
                    text_size: self.width, None
                    text: 'Garnitur'
                Label:
                    text_size: self.width, None
                    size_hint: 1, None
                    text: ' '       


        BoxLayout:
            orientation: 'horizontal'
            size_hint: (.95, .1)
            Button:
                text: 'Abbrechen'
                on_release: root.dismiss()
            Button:
                text: 'Weiter'

<ZutatenSpinner>
    Spinner:
        name: root.Zutatenart
        text: 'Weitere Zutat hinzufügen'
        values: root.zutatenart_list
        on_text: root.on_zutaten_spinner_select(self.text, self.name)

    Spinner:
        name: root.Zutat
        text: 'Bitte wählen'
        values: root.zutaten_list
        on_text: root.on_zutaten_spinner_select(self.text, self.name)

